[package]
name = "solid_engine_website"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "4.1.2"
dircpy = "0.3.7"
serde = { version = "1.0.127", features = ["derive"] }
notify = "4.0.17"
